import {
  Brain,
  Briefcase,
  CheckCircle,
  Eye,
  FileText,
  FileTextIcon,
  Hand,
  Heart,
  History,
  Home,
  List,
  Move,
  Scissors,
  Stethoscope,
  StickyNote,
  Target,
  TestTube,
  Zap,
} from "lucide-react";

export const SECTION_GROUPS = {
  essential: [
    {
      id: "vitals",
      name: "On Examination (Vitals)",
      icon: Stethoscope,
      required: true,
      active: true,
      toggle: false,
      defaultActive: true,
    },
    {
      id: "chiefComplaints",
      name: "Present Illness History",
      icon: FileText,
      required: true,
      active: true,
      toggle: false,
      defaultActive: true,
    },
    {
      id: "onObservation",
      name: "On Observation",
      icon: Eye,
      required: true,
      active: true,
      toggle: false,
      defaultActive: true,
    },
  ],

  history: [
    {
      id: "historyOfIllness",
      name: "Past History",
      icon: History,
      required: false,
      active: true,
      toggle: true,
      defaultActive: true,
    },
    {
      id: "medicalHistory",
      name: "Medical History",
      icon: Heart,
      required: false,
      active: true,
      toggle: true,
      defaultActive: true,
    },
    {
      id: "painHistory",
      name: "Pain History",
      icon: Zap,
      required: false,
      active: true,
      toggle: true,
      defaultActive: true,
    },
    {
      id: "surgicalHistory",
      name: "Surgical History",
      icon: Scissors,
      required: false,
      active: false,
      toggle: true,
      defaultActive: false,
    },
    {
      id: "occupationalHistory",
      name: "Occupational History",
      icon: Briefcase,
      required: false,
      active: false,
      toggle: true,
      defaultActive: false,
    },
    {
      id: "environmentalHistory",
      name: "Environmental History",
      icon: Home,
      required: false,
      active: false,
      toggle: true,
      defaultActive: false,
    },
  ],

  examination: [
    {
      id: "motorExamination",
      name: "Motor Examination",
      icon: Move,
      required: false,
      active: true,
      toggle: true,
      defaultActive: true,
    },
    {
      id: "neurologicalExam",
      name: "Neurological Examination",
      icon: Brain,
      required: false,
      active: true,
      toggle: true,
      defaultActive: true,
    },
    {
      id: "onPalpation",
      name: "On Palpation",
      icon: Hand,
      required: false,
      active: true,
      toggle: true,
      defaultActive: true,
    },
    {
      id: "specialTests",
      name: "Special Tests",
      icon: TestTube,
      required: false,
      active: true,
      toggle: true,
      defaultActive: true,
    },
  ],

  assessment: [
    {
      id: "differentialDiagnosis",
      name: "Differential Diagnostics",
      icon: List,
      required: false,
      active: false,
      toggle: true,
      defaultActive: false,
    },
    {
      id: "investigations",
      name: "Investigations",
      icon: FileTextIcon,
      required: false,
      active: false,
      toggle: true,
      defaultActive: false,
    },
    {
      id: "provisionalDiagnosis",
      name: "Provisional Diagnosis",
      icon: CheckCircle,
      required: false,
      active: false,
      toggle: true,
      defaultActive: false,
    },
    {
      id: "physiotherapyMgmt",
      name: "Physiotherapy Management Plan",
      icon: Target,
      required: false,
      active: false,
      toggle: true,
      defaultActive: false,
    },
  ],

  documentation: [
    {
      id: "notes",
      name: "Additional Notes",
      icon: StickyNote,
      required: true,
      active: true,
      toggle: false,
      defaultActive: true,
    },
  ],
};
