name: Deploy Theracure Dashboard

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy to Utho Cloud via SSH
        uses: appleboy/ssh-action@master
        with:
          host: 157.20.214.173
          username: root
          key: ${{ secrets.UTHO_INSTANCE_PRIVAT_KEY }}
          script: |
            set -e

            echo "🎯 Switching to project directory"
            cd /var/www/html/Theracure-Dashboard

            echo "📥 Pulling latest code from Git"
            git pull origin main

            echo "🔐 Setting DATABASE_URL "
            export DATABASE_URL="${{ secrets.DATABASE_URL }}"

            echo "📦 Installing dependencies"
            pnpm install

            echo "⚙️ Building the application"
            pnpm build

            echo "🗄️ Running Prisma migrations"
            pnpm prisma migrate deploy || { echo "❌ Error: Failed to deploy Prisma migrations. Exiting."; exit 1; }

            echo "🧑‍💻 Installing Puppeteer Chrome"
            pnpm exec puppeteer browsers install chrome || { echo "❌ Error: Failed to install Chrome for Puppeteer. Exiting."; exit 1; }

            echo "🚀 Restarting application with PM2"
            pm2 startOrRestart /var/www/html/ecosystem.config.js --only dashboard

            echo "✅ PM2 status check"
            pm2 status

            echo "🎉 Deployment complete!"
